In [1]:
import numpy as np
a = np.random.randn(5)


In [2]:
print(a)

[ 0.23510234 -0.06839228  1.28161002  0.98573708  2.30157955]


In [3]:
# Shape of a 
print(a.shape)

(5,)


    ### A is called a Rank 1 array. it's neither a Row Vector nor a column vector 

In [5]:
# a.T is the transpose of a 
print(a.T)

[ 0.23510234 -0.06839228  1.28161002  0.98573708  2.30157955]


In [7]:
print(np.dot(a,a.T))

7.97142085811


In [8]:
# Now we will set a to be a (5,1) vector
a = np.random.randn(5,1)

In [9]:
print(a)

[[ 0.16695181]
 [-0.97475068]
 [ 1.92688499]
 [ 2.81687559]
 [-0.70245936]]


In [10]:
print(a.T)

[[ 0.16695181 -0.97475068  1.92688499  2.81687559 -0.70245936]]


In [14]:
print(np.dot(a,a.T))

[[ 0.02787291 -0.16273639  0.32169694  0.47028248 -0.11727686]
 [-0.16273639  0.95013889 -1.87823245 -2.7457514   0.68472274]
 [ 0.32169694 -1.87823245  3.71288575  5.42779529 -1.3535584 ]
 [ 0.47028248 -2.7457514   5.42779529  7.93478811 -1.97874063]
 [-0.11727686  0.68472274 -1.3535584  -1.97874063  0.49344915]]


In [17]:
 # We can check if a is a vector by using the assert function
assert(a.shape == (5,1))

In [19]:
# if for some reason you end up by a rank 1 array, you can reshape it 
a = a.reshape((1,5))

In [20]:
print(a)

[[ 0.16695181 -0.97475068  1.92688499  2.81687559 -0.70245936]]
